name: Test AWS OIDC Connection

on:
  workflow_dispatch:  # 수동 실행용 트리거

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{AWS_ROLE_NAME}}
          aws-region: ap-northeast-2

      - name: Verify identity with AWS STS
        run: aws sts get-caller-identity
