name: Test AWS OIDC Access

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print Secrets (for debugging only)
      run: |
        echo "AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}"
        echo "AWS_REGION=${{ secrets.AWS_REGION }}"
      shell: bash

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify Identity
      run: |
        aws sts get-caller-identity